### ISSUE TITLE
执行抓取脚本时报错

### ISSUE THREAD

**Issue by MengXin001** [hanchyhill/oceanMonitor#8]
网页可以打开，执行`node prSprider.js`和`node bule-koa.js`&`node index.js`时报错
均提示`internal/modules/cjs/loader.js:800
 throw err;`，loader.js这个文件第800行throw的t这个字符有问题但找不到具体的源文件，望解决感谢！
![报错截图](https://user-images.githubusercontent.com/54111871/72507590-1f93bf80-387f-11ea-9db8-62b7c128f071.png)
使用Nodejs12.14.0 npm6.13.4

**Comment by MengXin001** [comment]
**Readme中存在错误应执行**`node prSpider.js`

**Comment by hanchyhill** [comment]
> 
> 
> **Readme中存在错误应执行**`node prSpider.js`

谢谢指正，怎么会有人用这个程序。这程序抓取报文部分需要自己添加配置文件才能正常运行，主要是Mongodb数据库配置，ecmwf的api接口，还有气象内网的报文配置信息。

**Comment by MengXin001** [comment]
> > **Readme中存在错误应执行**`node prSpider.js`
> 
> 谢谢指正，怎么会有人用这个程序。这程序抓取报文部分需要自己添加配置文件才能正常运行，主要是Mongodb数据库配置，ecmwf的api接口，还有气象内网的报文配置信息。

虽然没在省局内网里，但自己学习气象看一些cimss的涡度风切图和风场扫描还是很方便的:laughing:
